# permissions for end users to view buildenvironments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: buildenvironment-viewer-role
rules:
- apiGroups:
  - buildkite.wirecube.net
  resources:
  - buildenvironments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - buildkite.wirecube.net
  resources:
  - buildenvironments/status
  verbs:
  - get
