# permissions for end users to view buildjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: buildjob-viewer-role
rules:
- apiGroups:
  - buildkite.wirecube.net
  resources:
  - buildjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - buildkite.wirecube.net
  resources:
  - buildjobs/status
  verbs:
  - get
